# Generated by Django 5.1.15 on 2026-06-22 16:52

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=300, verbose_name='Суд')),
                ('case_number', models.CharField(max_length=100, verbose_name='Номер дела')),
                ('decision_date', models.DateField(verbose_name='Дата решения')),
                ('thesis', models.CharField(max_length=500, verbose_name='Тезис')),
                ('text', models.TextField(blank=True, verbose_name='Текст / ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_cases', to='catalog.legalbranch', verbose_name='Отрасль права')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Судебная практика',
                'verbose_name_plural': 'Судебная практика',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('norm_type', models.CharField(choices=[('law', 'Федеральный закон'), ('code', 'Кодекс'), ('decree', 'Указ Президента'), ('resolution', 'Постановление Правительства'), ('order', 'Приказ'), ('other', 'Иное')], default='law', max_length=20, verbose_name='Вид НПА')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Статья')),
                ('text', models.TextField(verbose_name='Текст нормы')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='Источник')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='norms', to='catalog.legalbranch', verbose_name='Отрасль права')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Норма',
                'verbose_name_plural': 'Нормы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Тема заключения')),
                ('text', models.TextField(verbose_name='Текст заключения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Общедоступное')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opinions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('related_cases', models.ManyToManyField(blank=True, related_name='opinions', to='knowledge.courtcase', verbose_name='Связанная практика')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
                ('related_norms', models.ManyToManyField(blank=True, related_name='opinions', to='knowledge.norm', verbose_name='Связанные нормы')),
            ],
            options={
                'verbose_name': 'Правовое заключение',
                'verbose_name_plural': 'Правовые заключения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courtcase',
            name='related_norms',
            field=models.ManyToManyField(blank=True, related_name='court_cases', to='knowledge.norm', verbose_name='Связанные нормы'),
        ),
    ]
