# Generated by Django 5.1.15 on 2026-06-19 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('templates_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='СгенерированныйДокумент',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('значения', models.JSONField(default=dict, verbose_name='Значения переменных')),
                ('файл_docx', models.FileField(blank=True, upload_to='documents/docx/', verbose_name='Файл .docx')),
                ('файл_pdf', models.FileField(blank=True, upload_to='documents/pdf/', verbose_name='Файл .pdf')),
                ('статус', models.CharField(choices=[('черновик', 'Черновик'), ('готов', 'Готов'), ('ошибка', 'Ошибка генерации')], default='черновик', max_length=10, verbose_name='Статус')),
                ('ошибка', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('создан', models.DateTimeField(auto_now_add=True)),
                ('изменён', models.DateTimeField(auto_now=True)),
                ('автор', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='документы', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('контрагент', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='документы', to='catalog.контрагент', verbose_name='Контрагент')),
                ('шаблон', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='документы', to='templates_engine.шаблондокумента', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-создан'],
            },
        ),
    ]
