# Generated by Django 5.1.15 on 2026-06-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ШаблонДокумента',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=255, verbose_name='Название')),
                ('тип', models.CharField(choices=[('услуги', 'Договор оказания услуг'), ('поставка', 'Договор поставки'), ('претензия', 'Претензия'), ('доверенность', 'Доверенность'), ('иск', 'Исковое заявление'), ('иное', 'Иное')], default='иное', max_length=20, verbose_name='Тип документа')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
                ('файл', models.FileField(upload_to='templates/', verbose_name='Файл шаблона (.docx)')),
                ('активен', models.BooleanField(default=True, verbose_name='Активен')),
                ('создан', models.DateTimeField(auto_now_add=True)),
                ('изменён', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['название'],
            },
        ),
        migrations.CreateModel(
            name='Переменная',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ключ', models.CharField(max_length=100, verbose_name='Ключ (тег в шаблоне)')),
                ('подпись', models.CharField(max_length=255, verbose_name='Подпись в форме')),
                ('тип_данных', models.CharField(choices=[('str', 'Текст'), ('date', 'Дата'), ('decimal', 'Сумма'), ('int', 'Целое число'), ('choice', 'Выбор из списка')], default='str', max_length=10, verbose_name='Тип данных')),
                ('обязательное', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('значение_по_умолчанию', models.CharField(blank=True, max_length=255, verbose_name='Значение по умолчанию')),
                ('порядок', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('шаблон', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='переменные', to='templates_engine.шаблондокумента', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
                'ordering': ['порядок', 'ключ'],
                'unique_together': {('шаблон', 'ключ')},
            },
        ),
    ]
