# Generated by Django 5.1.15 on 2026-06-19 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Контрагент',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('наименование', models.CharField(max_length=255, verbose_name='Наименование')),
                ('тип', models.CharField(choices=[('юр', 'Юридическое лицо'), ('физ', 'Физическое лицо / ИП')], default='юр', max_length=3, verbose_name='Тип')),
                ('инн', models.CharField(max_length=12, verbose_name='ИНН')),
                ('кпп', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('адрес', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('телефон', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('создан', models.DateTimeField(auto_now_add=True)),
                ('изменён', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['наименование'],
            },
        ),
        migrations.CreateModel(
            name='Юрист',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('должность', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('телефон', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='юрист', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Юрист',
                'verbose_name_plural': 'Юристы',
            },
        ),
    ]
