# Generated by Django 5.1.15 on 2026-06-20 10:14

import apps.catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='контрагент',
            name='инн',
            field=models.CharField(max_length=12, validators=[apps.catalog.validators.валидатор_инн], verbose_name='ИНН'),
        ),
    ]
